
-- q1 . what is the revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as revenue from cleaned_customer_data
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

-- select * from cleaned_customer_data

select customer_id,purchase_amount from cleaned_customer_data where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from cleaned_customer_data)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(AVG(review_rating),2) as avg_product_rating 
 from cleaned_customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, ROUND(avg(purchase_amount),2)
 from cleaned_customer_data
 where shipping_type in ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue 
from cleaned_customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- select * from cleaned_customer_data
select top 5 item_purchased,
ROUND(100 * sum(
    CASE WHEN discount_applied = 'Yes'
    THEN 1 
    else 0
    END) / COUNT(*),2) as discount_rate
from cleaned_customer_data
GROUP BY item_purchased 
ORDER BY discount_rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 



--Q8. What are the top 3 most purchased products within each category? 
with item_count as (
    select category,item_purchased,
     COUNT(customer_id) as total_orders,
     ROW_NUMBER() OVER(PARTITION BY category ORDER by COUNT(customer_id) desc) as item_rank
     from cleaned_customer_data
     GROUP BY category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_count where item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
 from cleaned_customer_data
 where previous_purchases > 5
 GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as revenue
from cleaned_customer_data
GROUP by age_group
order by revenue desc
